"""Export a canvas graph as runnable Python code.

The generated code is idiomatic Mosaic: it imports the necessary node classes,
instantiates them with the user-configured parameters, and executes the pipeline.

For **linear** pipelines the code uses Mosaic's declarative ``Pipeline([...])``
API. For graphs with branches, merges, or multiple inputs it falls back to an
explicit topological execution loop that mirrors the canvas executor.
"""

from __future__ import annotations

import json
from typing import Any

from mosaic_canvas.graph import Graph

__all__ = ["export_python", "detect_linear_chain"]


# Parameters that should be rendered as Python literals, not strings.
_PYTHON_LITERAL_TYPES = {"int", "float", "bool"}


def _format_param_value(value: Any, ui_type: str) -> str:
    """Render a single parameter value as a Python expression string."""
    if value is None:
        return "None"
    if ui_type == "bool":
        if isinstance(value, str):
            return "True" if value.lower() in ("true", "1", "yes") else "False"
        return repr(bool(value))
    if ui_type == "int":
        try:
            return repr(int(float(value)))
        except (ValueError, TypeError):
            return repr(value)
    if ui_type == "float":
        try:
            return repr(float(value))
        except (ValueError, TypeError):
            return repr(value)
    if isinstance(value, str):
        return repr(value)
    return repr(value)


def _format_params(
    params: dict[str, Any],
    param_types: dict[str, str],
) -> str:
    """Format a params dict as constructor keyword arguments."""
    if not params:
        return ""
    parts: list[str] = []
    for k, v in params.items():
        ui_type = param_types.get(k, "string")
        if v is None or v == "":
            continue
        parts.append(f"{k}={_format_param_value(v, ui_type)}")
    return ", ".join(parts)


def _get_param_types(node_type: str) -> dict[str, str]:
    """Look up UI types for a node's parameters."""
    from mosaic_canvas.introspect import get_node_info

    info = get_node_info(node_type)
    if info is None:
        return {}
    return {p.name: p.type for p in info.params}


def _get_input_field_types(node_type: str) -> dict[str, str]:
    """Look up UI types for a node's runtime input fields."""
    from mosaic_canvas.introspect import get_node_info

    info = get_node_info(node_type)
    if info is None:
        return {}
    return {f.name: f.type for f in info.input_fields}


def _node_var_name(node_id: str, index: int) -> str:
    """Generate a clean variable name for a node."""
    return f"node_{index}"


def _class_import_path(node_type: str) -> tuple[str, str]:
    """Return (module_path, class_name) for importing a node by type.

    Falls back to ``registry.get`` if the import path is unknown.
    """
    from mosaic_canvas.introspect import get_node_info

    info = get_node_info(node_type)
    if info is None:
        return "", node_type
    # Use the actual module path if available; fall back to mosaic.nodes
    module = info.module or "mosaic.nodes"
    return module, info.class_name


def detect_linear_chain(graph: Graph) -> list[str] | None:
    """If the graph is a single linear chain, return node ids in order.

    A linear chain has exactly one source, one sink, and every intermediate
    node has exactly one predecessor and one successor. Returns ``None`` if
    the graph is not a simple linear chain.
    """
    if not graph.nodes:
        return None

    sources = graph.sources()
    if len(sources) != 1:
        return None

    chain: list[str] = []
    current = sources[0]
    visited: set[str] = set()

    while current is not None:
        if current in visited:
            return None  # cycle (shouldn't happen, but guard)
        visited.add(current)
        chain.append(current)
        succs = graph.successors(current)
        preds = graph.predecessors(current)
        # Every node except the first must have exactly one predecessor
        if len(preds) > 1:
            return None
        if len(succs) == 0:
            break
        if len(succs) > 1:
            return None
        current = succs[0]

    if len(chain) != len(graph.nodes):
        return None
    return chain


def export_python(graph: Graph) -> str:
    """Generate runnable Python code from a :class:`Graph`."""
    lines: list[str] = []
    lines.append('"""')
    lines.append(f"Mosaic pipeline: {graph.name}")
    lines.append("Auto-generated by Mosaic Canvas.")
    lines.append('"""')
    lines.append("")

    # Collect unique node types for imports
    node_types = {n.type for n in graph.nodes}
    import_map: dict[str, set[str]] = {}  # module -> set of class names
    for nt in node_types:
        module, cls_name = _class_import_path(nt)
        if module:
            import_map.setdefault(module, set()).add(cls_name)

    # Build class-name -> node-type mapping for instantiation
    type_to_class: dict[str, str] = {}
    for nt in node_types:
        _, cls_name = _class_import_path(nt)
        type_to_class[nt] = cls_name

    # Write imports
    lines.append("from mosaic import MosaicData, Pipeline, Branch, Merge")
    for module, classes in sorted(import_map.items()):
        sorted_classes = sorted(classes)
        lines.append(f"from {module} import {', '.join(sorted_classes)}")
    lines.append("")
    lines.append("")

    # Instantiate nodes
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Node instantiation")
    lines.append("# ---------------------------------------------------------------------------")
    var_map: dict[str, str] = {}
    for i, gnode in enumerate(graph.nodes):
        var = _node_var_name(gnode.id, i)
        var_map[gnode.id] = var
        cls_name = type_to_class.get(gnode.type, gnode.type)
        param_types = _get_param_types(gnode.type)
        params_str = _format_params(gnode.params, param_types)
        if params_str:
            lines.append(f'{var} = {cls_name}({params_str})')
        else:
            lines.append(f'{var} = {cls_name}()')
    lines.append("")

    # Build pipeline input (include source node input_params)
    source_input_params: dict[str, Any] = {}
    source_input_types: dict[str, str] = {}
    for gnode in graph.nodes:
        if not graph.predecessors(gnode.id) and gnode.input_params:
            field_types = _get_input_field_types(gnode.type)
            for k, v in gnode.input_params.items():
                source_input_params[k] = v
                if k in field_types:
                    source_input_types[k] = field_types[k]
    all_input = {**graph.input.data, **source_input_params}
    if all_input:
        lines.append("# ---------------------------------------------------------------------------")
        lines.append("# Pipeline input")
        lines.append("# ---------------------------------------------------------------------------")
        input_parts: list[str] = []
        for k, v in all_input.items():
            if k in source_input_types:
                ui_type = source_input_types[k]
                input_parts.append(f"{k}={_format_param_value(v, ui_type)}")
            elif isinstance(v, str):
                input_parts.append(f"{k}={v!r}")
            elif isinstance(v, (int, float, bool)):
                input_parts.append(f"{k}={v!r}")
            else:
                input_parts.append(f"{k}={v!r}")
        lines.append(f"input_data = MosaicData({', '.join(input_parts)})")
        lines.append("")

    # Generate execution code
    chain = detect_linear_chain(graph)

    if chain is not None and len(chain) > 0:
        # Linear pipeline — use idiomatic Pipeline API
        lines.append("# ---------------------------------------------------------------------------")
        lines.append("# Build & run pipeline (linear chain)")
        lines.append("# ---------------------------------------------------------------------------")
        element_vars = [var_map[nid] for nid in chain]
        lines.append(f'pipeline = Pipeline({graph.name!r}, [')
        for ev in element_vars:
            lines.append(f"    {ev},")
        lines.append("])")
        lines.append("")
        if all_input:
            lines.append("result = pipeline.execute_result(input_data)")
        else:
            lines.append("result = pipeline.execute_result(MosaicData())")
        lines.append("")
        lines.append("print(result.summary())")
    else:
        # General graph — explicit topological execution
        lines.append("# ---------------------------------------------------------------------------")
        lines.append("# Execute pipeline (graph topology)")
        lines.append("# ---------------------------------------------------------------------------")
        lines.append("import time")
        lines.append("")
        lines.append("outputs = {}")
        try:
            order = graph.topological_order()
        except ValueError:
            order = [n.id for n in graph.nodes]

        for nid in order:
            gnode = graph.get_node(nid)
            assert gnode is not None
            var = var_map[nid]
            preds = graph.predecessors(nid)

            lines.append(f"# {gnode.type} ({gnode.label or gnode.id})")
            if not preds:
                if all_input:
                    lines.append(f"_input = input_data")
                else:
                    lines.append(f"_input = MosaicData()")
            else:
                lines.append(f"_input = MosaicData()")
                for pid in preds:
                    lines.append(f"for _k, _v in outputs[{pid!r}].items():")
                    lines.append(f"    _input[_k] = _v")

            # Merge per-node runtime input params (coerced to proper types)
            if gnode.input_params:
                field_types = _get_input_field_types(gnode.type)
                for k, v in gnode.input_params.items():
                    if v is None or v == "":
                        continue
                    ui_type = field_types.get(k, "string")
                    lines.append(f"_input[{k!r}] = {_format_param_value(v, ui_type)}")

            lines.append(f"t0 = time.perf_counter()")
            lines.append(f"outputs[{nid!r}] = {var}(_input)")
            lines.append(f"print(f'{gnode.type} done in {{time.perf_counter() - t0:.2f}}s')")
            lines.append("")

        # Final output
        sinks = graph.sinks()
        if len(sinks) == 1:
            lines.append(f"result = outputs[{sinks[0]!r}]")
        elif sinks:
            lines.append("result = {")
            for sid in sinks:
                lines.append(f"    {sid!r}: outputs[{sid!r}],")
            lines.append("}")
        else:
            lines.append("result = None")
        lines.append("")
        lines.append("print('Pipeline complete.')")

    lines.append("")
    return "\n".join(lines)
